# Generated by Django 5.2.6 on 2025-09-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accepteddomain',
            options={'verbose_name_plural': 'Domínios aceites'},
        ),
        migrations.AlterModelOptions(
            name='customuser',
            options={'verbose_name_plural': 'Usuários (Modelo customizado)'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Perfis'},
        ),
        migrations.AlterModelOptions(
            name='subsidiary',
            options={'verbose_name_plural': 'subsidiárias'},
        ),
        migrations.AddField(
            model_name='accepteddomain',
            name='is_sso_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='acronym',
            field=models.CharField(max_length=10, verbose_name='Acrónimo'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='domain',
            field=models.CharField(max_length=100, unique=True, verbose_name='Domínio'),
        ),
        migrations.AlterField(
            model_name='subsidiary',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
