# Generated by Django 5.2.6 on 2025-09-15 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0002_alter_accepteddomain_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accepteddomain',
            name='discovery_host',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
