# Generated by Django 5.2.6 on 2026-09-21 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0006_remove_profile_department_division_profile_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.division'),
        ),
    ]
