# Generated by Django 5.2.6 on 2025-09-12 11:31

import utils.identifiers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Norms',
            fields=[
                ('id', models.UUIDField(default=utils.identifiers.generate_sequential_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('revoked', 'Revoked')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('legal_basis', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('policy', 'Policy'), ('regulation', 'Regulation'), ('technical_standard', 'Technical Standard')], max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Procedures',
            fields=[
                ('id', models.UUIDField(default=utils.identifiers.generate_sequential_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('revoked', 'Revoked')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('current_version', models.PositiveIntegerField(default=1)),
                ('steps', models.JSONField(default=list)),
                ('estimated_duration', models.DurationField(blank=True, null=True)),
                ('criticality', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
