# Generated by Django 5.2.6 on 2025-09-12 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('norm_proc_app', '0001_initial'),
        ('users_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='norms',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='norms',
            name='responsible_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.department'),
        ),
        migrations.AddField(
            model_name='procedures',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedures',
            name='operational_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users_app.department'),
        ),
    ]
