# Generated by Django 5.2.6 on 2025-09-14 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='norms',
            options={'verbose_name_plural': 'Normas'},
        ),
        migrations.AlterModelOptions(
            name='procedures',
            options={'verbose_name_plural': 'Procedimentos'},
        ),
    ]
