# Generated by Django 5.2.6 on 2026-01-01 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0003_alter_norms_options_alter_procedures_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='norms',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='procedures',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
