# Generated by Django 5.2.6 on 2026-07-22 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0004_norms_file_procedures_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='norms',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='norm_proc_app.norms'),
        ),
        migrations.AddField(
            model_name='procedures',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='norm_proc_app.procedures'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='current_version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='norms',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('revoked', 'Revoked')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='current_version',
            field=models.CharField(default='1.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('revoked', 'Revoked')], default='draft', max_length=50),
        ),
    ]
