# Generated by Django 5.2.6 on 2026-07-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0005_norms_parent_procedures_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norms',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('revogado', 'Revogado')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('em_analise', 'Em análise'), ('aprovado', 'Aprovado'), ('revogado', 'Revogado')], default='draft', max_length=50),
        ),
    ]
