# Generated by Django 5.2.6 on 2026-07-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0006_alter_norms_status_alter_procedures_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norms',
            name='document_type',
            field=models.CharField(choices=[('politica', 'Política'), ('regulamento', 'Regulamento'), ('norma_tecnica', 'Norma técnica')], max_length=100),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='criticality',
            field=models.CharField(choices=[('baixo', 'Baixo'), ('medio', 'Médio'), ('alto', 'Alto')], max_length=50),
        ),
    ]
