# Generated by Django 5.2.6 on 2026-07-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0007_alter_norms_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='norms',
            name='description',
        ),
        migrations.RemoveField(
            model_name='procedures',
            name='description',
        ),
        migrations.AddField(
            model_name='norms',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='procedures',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='norms',
            name='document_type',
            field=models.CharField(choices=[('policy', 'Policy'), ('regulation', 'Regulation'), ('technical_standard', 'Technical Standard')], max_length=100),
        ),
        migrations.AlterField(
            model_name='norms',
            name='legal_basis',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='norms',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('revoked', 'Revoked')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='criticality',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=50),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('revoked', 'Revoked')], default='draft', max_length=50),
        ),
    ]
