# Generated by Django 5.2.6 on 2026-08-26 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0008_remove_norms_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norms',
            name='legal_basis',
            field=models.CharField(blank=True, default=''),
        ),
    ]
