# Generated by Django 5.2.6 on 2026-09-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0009_alter_norms_legal_basis'),
    ]

    operations = [
        migrations.AddField(
            model_name='norms',
            name='Classification_level',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential')], default='internal', max_length=50),
        ),
        migrations.AddField(
            model_name='procedures',
            name='Classification_level',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential')], default='internal', max_length=50),
        ),
    ]
