# Generated by Django 5.2.6 on 2026-09-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0010_norms_classification_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norms',
            name='Classification_level',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential')], default='internal', max_length=50, verbose_name='Nível de classificação'),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='Classification_level',
            field=models.CharField(choices=[('public', 'Public'), ('internal', 'Internal'), ('confidential', 'Confidential')], default='internal', max_length=50, verbose_name='Nível de classificação'),
        ),
    ]
