# Generated by Django 5.2.6 on 2026-09-10 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0011_alter_norms_classification_level_and_more'),
        ('users_app', '0005_alter_customuser_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='norms',
            name='drafted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_drafted_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedures',
            name='drafted_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_drafted_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='norms',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_authored_documents', to='users_app.department'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='responsible_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='norms_responsible_documents', to='users_app.department'),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_authored_documents', to='users_app.department'),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='operational_department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures_operational_documents', to='users_app.department'),
        ),
    ]
