# Generated by Django 5.2.6 on 2026-09-10 12:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0012_norms_drafted_by_procedures_drafted_by_and_more'),
        ('users_app', '0005_alter_customuser_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='norms',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='norms',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='norms',
            name='document_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned_documents', to='users_app.department'),
        ),
        migrations.AddField(
            model_name='norms',
            name='next_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima revisão'),
        ),
        migrations.AddField(
            model_name='norms',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedures',
            name='approved_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='procedures',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='procedures',
            name='document_owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned_documents', to='users_app.department'),
        ),
        migrations.AddField(
            model_name='procedures',
            name='next_review_date',
            field=models.DateField(blank=True, null=True, verbose_name='Próxima revisão'),
        ),
        migrations.AddField(
            model_name='procedures',
            name='reviewed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
