# Generated by Django 5.2.6 on 2026-09-11 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0013_norms_approved_by_norms_code_norms_document_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='norms',
            name='legal_basis',
        ),
    ]
