# Generated by Django 5.2.6 on 2026-09-14 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0014_remove_norms_legal_basis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='norms',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
