# Generated by Django 5.2.6 on 2026-09-14 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0015_alter_norms_approved_by_alter_procedures_approved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='norms',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed_documents', to=settings.AUTH_USER_MODEL),
        ),
    ]
