# Generated by Django 5.2.6 on 2026-09-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0016_alter_norms_reviewed_by_alter_procedures_reviewed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='norms',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código do documento'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('pending_approval', 'Pending approval'), ('revoked', 'Revoked')], default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código do documento'),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('pending_approval', 'Pending approval'), ('revoked', 'Revoked')], default='draft', max_length=50),
        ),
    ]
