# Generated by Django 5.2.6 on 2026-09-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0017_alter_norms_code_alter_norms_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='norms',
            name='content',
        ),
        migrations.RemoveField(
            model_name='procedures',
            name='content',
        ),
        migrations.AddField(
            model_name='norms',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='procedures',
            name='Description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='Classification_level',
            field=models.CharField(choices=[('publico', 'Público'), ('interno', 'Interno'), ('confidencial', 'Confidencial')], default='interno', max_length=50, verbose_name='Nível de classificação'),
        ),
        migrations.AlterField(
            model_name='norms',
            name='document_type',
            field=models.CharField(choices=[('politica', 'Política'), ('regulation', 'Regulation'), ('technical_standard', 'Technical Standard')], max_length=100),
        ),
        migrations.AlterField(
            model_name='norms',
            name='status',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('expirado', 'Expirado'), ('revogado', 'Revogado')], default='vigente', max_length=50),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='Classification_level',
            field=models.CharField(choices=[('publico', 'Público'), ('interno', 'Interno'), ('confidencial', 'Confidencial')], default='interno', max_length=50, verbose_name='Nível de classificação'),
        ),
        migrations.AlterField(
            model_name='procedures',
            name='status',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('expirado', 'Expirado'), ('revogado', 'Revogado')], default='vigente', max_length=50),
        ),
    ]
