# Generated by Django 5.2.6 on 2026-09-30 10:24

import django.db.models.deletion
import utils.identifiers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0018_remove_norms_content_remove_procedures_content_and_more'),
        ('users_app', '0007_alter_profile_division'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='procedures',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='procedures',
            name='author',
        ),
        migrations.RemoveField(
            model_name='procedures',
            name='document_owner',
        ),
        migrations.RemoveField(
            model_name='procedures',
            name='drafted_by',
        ),
        migrations.RemoveField(
            model_name='procedures',
            name='operational_department',
        ),
        migrations.RemoveField(
            model_name='procedures',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='procedures',
            name='reviewed_by',
        ),
        migrations.CreateModel(
            name='BaseDocument',
            fields=[
                ('id', models.UUIDField(default=utils.identifiers.generate_sequential_uuid, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('Description', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('vigente', 'Vigente'), ('expirado', 'Expirado'), ('revogado', 'Revogado')], default='vigente', max_length=50)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('Classification_level', models.CharField(choices=[('publico', 'Público'), ('interno', 'Interno'), ('confidencial', 'Confidencial'), ('restrito', 'Restrito')], default='interno', max_length=50, verbose_name='Nível de classificação')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('current_version', models.CharField(default='1.0', max_length=10)),
                ('next_review_date', models.DateField(blank=True, null=True, verbose_name='Próxima revisão')),
                ('document_type', models.CharField(choices=[('norm', 'Norma'), ('procedure', 'Procedimento'), ('policy', 'Política'), ('regulation', 'Regulamento'), ('manual', 'Manual'), ('guide', 'Guia'), ('sop', ' Standard Operating Procedure')], default='norm', max_length=50, verbose_name='Tipo de documento')),
                ('code', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Código do documento')),
                ('Recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_app.department', verbose_name='Destinatário')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_approved_documents', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_authored_documents', to='users_app.department')),
                ('document_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_owned_documents', to='users_app.department')),
                ('drafted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_drafted_documents', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='norm_proc_app.basedocument')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Norms',
        ),
        migrations.DeleteModel(
            name='Procedures',
        ),
    ]
