# Generated by Django 5.2.6 on 2026-09-30 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0019_remove_procedures_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedocument',
            name='file',
            field=models.FileField(default='documents/default.pdf', upload_to='documents/'),
        ),
    ]
