# Generated by Django 5.2.6 on 2026-10-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0020_alter_basedocument_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedocument',
            name='expired_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basedocument',
            name='Description',
            field=models.TextField(blank=True, default='', verbose_name='Descrição'),
        ),
    ]
