# Generated by Django 5.2.6 on 2026-10-01 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0021_basedocument_expired_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedocument',
            name='Description',
            field=models.TextField(blank=True, verbose_name='Descrição'),
        ),
    ]
