# Generated by Django 5.2.6 on 2026-10-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0022_alter_basedocument_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basedocument',
            name='expired_at',
        ),
        migrations.AlterField(
            model_name='basedocument',
            name='file',
            field=models.FileField(upload_to='documents/', verbose_name='Arquivo do documento'),
        ),
        migrations.AlterField(
            model_name='basedocument',
            name='status',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('revogado', 'Revogado')], default='vigente', max_length=50),
        ),
    ]
