# Generated by Django 5.2.6 on 2026-10-05 11:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('norm_proc_app', '0023_remove_basedocument_expired_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basedocument',
            old_name='Classification_level',
            new_name='classification_level',
        ),
        migrations.RenameField(
            model_name='basedocument',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='basedocument',
            old_name='Recipient',
            new_name='recipient',
        ),
        migrations.AlterField(
            model_name='basedocument',
            name='created_at',
            field=models.DateTimeField(verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='basedocument',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='basedocument',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de revogação'),
        ),
    ]
